# generated by datamodel-codegen:
#   filename:  config.json
#   timestamp: 2025-05-24T07:56:03+00:00

from __future__ import annotations

from pydantic import BaseModel


class Images(BaseModel):
    project: str
    bucket: str


class Spreadsheet(BaseModel):
    folder_id: str
    name: str


class Search(BaseModel):
    result_increment: int
    max_results_for_creative_commons: int
    max_results_for_url: int
    max_results_for_text: int


class Width(BaseModel):
    number: int
    image: int
    name: int
    page: int
    site: int
    match: int
    license: int


class SheetStyle(BaseModel):
    match_count: int
    width: Width
    height: int


class Model(BaseModel):
    images: Images
    spreadsheet: Spreadsheet
    search: Search
    sheet_style: SheetStyle
