FROM python:3.12-slim

# Avoid .pyc files and enable real-time logs
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# System dependencies
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# Use the next lines instead if the following dependencies are needed
# build-essential: Needed only if your Python packages include C extensions (e.g. NumPy, psycopg2).
# libpq-dev: Required only if your app uses PostgreSQL with psycopg2.
# curl: Only needed if your app or script explicitly uses it.
# RUN apt-get update && apt-get install -y \
#    build-essential \
#    libpq-dev \
#    curl \
#    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Pre-copy requirements to leverage Docker layer caching
COPY backend/requirements.txt ./backend/requirements.txt
RUN pip install --upgrade pip && pip install -r backend/requirements.txt pydevd_pycharm

# Copy the rest of the app code
COPY backend/ ./backend/

# Set Python path so that you can do 'import backend.module'
ENV PYTHONPATH=/app

CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000"]