FROM --platform=linux/arm64 node:20-slim

WORKDIR /app/web-ui

COPY web-ui/package*.json ./

RUN npm ci --platform=linux --arch=x64

COPY web-ui/ ./

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
