// THIS FILE IS AUTO-GENERATED - DO NOT EDIT
// Generated by generate_types.py

export interface ImageRow {
  id: string;
  number: number;
  rank: number;
  thumbnail_url: string;
  selected_match: MatchRow | null;
  best_match: MatchRow | null;
  used_in: string | null;
  comment: string | null;
  replacement_page_url: string | null;
}

export interface MatchRow {
  id: number;
  rank: number;
  image_url: string;
  page_url: string;
  title: string;
  matching_type: string;
  license_url: string | null;
  attribution: string | null;
  licensed_by: string | null;
}
