// THIS FILE IS AUTO-GENERATED - DO NOT EDIT
// Generated by generate_types.py

export interface ImageRow {
  id: string;
  thumbnail_url: string;
  used_in: string | null;
  best_page_url: string | null;
  image_url: string | null;
  license_url: string | null;
  attribution: string | null;
  licensed_by: string | null;
  matching_type: string | null;
  comment: string | null;
}
