#!/usr/bin/env python3
"""
Script to automatically generate TypeScript interfaces from Python Pydantic models-frontend.
This helps keep frontend and backend types in sync.

Run this script when you update your Pydantic models-frontend to regenerate the TypeScript types.
"""

import importlib
import inspect
import os
import sys
from typing import Dict, List, Any, Optional, Set, Type, Union

# Add the project root to the Python path
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

# Import the Pydantic models-frontend
from backend.api.image_rows import ImageRow
from pydantic import BaseModel

# Path to the TypeScript output file
TS_OUTPUT_FILE = "../web-ui/src/components/generated-types.ts"

# Mapping of Python types to TypeScript types
TYPE_MAPPING = {
    'str': 'string',
    'int': 'number',
    'float': 'number',
    'bool': 'boolean',
    'list': 'Array',
    'dict': 'Record<string, any>',
    'Optional': 'Optional',
    'Any': 'any',
    'None': 'null',
}

def get_typescript_type(python_type: Any) -> str:
    """Convert a Python type annotation to TypeScript."""
    # Check if it's an Optional type (Union with None)
    if hasattr(python_type, "__origin__") and python_type.__origin__ is Union:
        # In Python 3.10+, Optional[T] is implemented as Union[T, None]
        if type(None) in python_type.__args__:
            # Get the non-None type from the Union
            non_none_types = [t for t in python_type.__args__ if t is not type(None)]
            if len(non_none_types) == 1:
                return f"{get_typescript_type(non_none_types[0])} | null"
            else:
                # Handle Union with multiple types and None
                types = [get_typescript_type(t) for t in non_none_types]
                return f"({' | '.join(types)}) | null"
    
    if hasattr(python_type, "__origin__"):
        # Handle generic types like List, Dict
        origin = python_type.__origin__
        if origin is list:
            arg_type = get_typescript_type(python_type.__args__[0])
            return f"{arg_type}[]"
        elif origin is dict:
            key_type = get_typescript_type(python_type.__args__[0])
            value_type = get_typescript_type(python_type.__args__[1])
            return f"Record<{key_type}, {value_type}>"
    
    # Handle direct types
    type_name = getattr(python_type, "__name__", str(python_type))
    if type_name in TYPE_MAPPING:
        return TYPE_MAPPING[type_name]
    
    # For custom Pydantic models, use the class name
    if inspect.isclass(python_type) and issubclass(python_type, BaseModel):
        return python_type.__name__
    
    # Default to 'any' for types we can't map
    return "any"

def generate_typescript_interface(model_class: Type[BaseModel]) -> str:
    """Generate TypeScript interface from a Pydantic model."""
    lines = [f"export interface {model_class.__name__} {{"]
    
    for field_name, field in model_class.__annotations__.items():
        ts_type = get_typescript_type(field)
        lines.append(f"  {field_name}: {ts_type};")
    
    lines.append("}")
    return "\n".join(lines)

def main():
    """Generate TypeScript interfaces from Pydantic models-frontend."""
    models = [ImageRow]  # Add more models-frontend as needed
    
    # Generate TypeScript code
    ts_code = [
        "// THIS FILE IS AUTO-GENERATED - DO NOT EDIT",
        "// Generated by generate_types.py",
        "",
    ]
    
    for model in models:
        ts_code.append(generate_typescript_interface(model))
        ts_code.append("")  # Add a blank line between interfaces
    
    # Write to the output file
    os.makedirs(os.path.dirname(TS_OUTPUT_FILE), exist_ok=True)
    with open(TS_OUTPUT_FILE, "w") as f:
        f.write("\n".join(ts_code))
    
    print(f"TypeScript interfaces generated in {TS_OUTPUT_FILE}")

if __name__ == "__main__":
    main()
