# generated by datamodel-codegen:
#   filename:  config.json
#   timestamp: 2025-05-26T20:36:50+00:00

from __future__ import annotations

from pydantic import BaseModel


class Thumbnail(BaseModel):
    width: int
    height: int


class Width(BaseModel):
    number: int
    image: int
    name: int
    page: int
    site: int
    match: int
    license: int


class SheetStyle(BaseModel):
    match_count: int
    width: Width
    height: int


class Model(BaseModel):
    google_project_id: str
    google_bucket_id: str
    google_folder_id: str
    spreadsheet_name: str
    attributions_name: str
    max_search_results: int
    thumbnail: Thumbnail
    sheet_style: SheetStyle
